cors:
  originPatterns: http://localhost:5173


spring:

  # Configurações para o banco de dados
  datasource:
    url: jdbc:postgresql://db:5432/mailsender?serverTimezone=UTC
    username: postgres
    password: MailSender123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configurações para o envio de e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: syonet.desafio.gabrielmoreno@gmail.com
    password: mnlwpkqqsrqrmbcd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
